[project]
name = "docker-nocli"
version = "0.1.1"
description = "The backend of docker-nocli"
readme = ""
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.121.2",
    "uvicorn>=0.38.0",
]
